language: android

dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29

before_script: ./.travis-pre.sh

script: ./.travis-build.sh

# TODO: Consider using a Travis release provider (e.g. GitHub Releases).
# https://docs.travis-ci.com/user/deployments
# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: script
  install: skip
  script: ./.travis-deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|develop)$

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
