language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - android-21
  - sys-img-armeabi-v7a-android-21
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_script:
- mkdir .travis
- chmod +x .travis-device-post.sh
- chmod +x .travis-device-pre.sh
- chmod +x .travis.sh

before_install:
- ./.travis-device-pre.sh
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager --update
- yes | sdkmanager --licenses

script:
- ./.travis.sh
- ./.travis-device-post.sh

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

