# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

default_platform(:android)

platform :android do

    # Runs ktlint before doing any distribution
    before_all do
      Dotenv.overload '.env'
    #   sh("./gradlew", "ktlint")
    end

    desc "Submit a new beta build to Firebase Beta"
    lane :qa do |options|
      release_notes = options[:release_notes] ? "#{options[:release_notes]}" : nil

      if not release_notes
        UI.user_error! "'release_notes' param must be supplied"
        next
      end
      gradle(task: "clean")
      gradle(task: "assembleRelease")
       firebase_app_distribution(
         app: "1:83753990150:android:770193bd9ffeb14e83eb87",
         groups: "openebooks-qa",
         release_notes: "#{release_notes}",
         firebase_cli_path: ENV["FIREBASE_CLI_PATH"])
       slack(
        message: "New Open eBooks Android build available on firebase",
        slack_url: ENV['SLACK_WEBHOOK_URL'],
        success: true,
        channel: "#simplified-releases",
        default_payloads: [],
        payload: {
          "Release notes" => :release_notes
        }
       )
    end

     # This needs to be tested as the .aab files have dynamic naming
     # desc "Deploy a new version to the Google Play"
     # lane :prod do |options|
     #   release_notes = options[:release_notes] ? "#{options[:release_notes]}" : nil
     #   tag = options[:tag] ? "#{options[:tag]}" : nil

     #   if not release_notes
     #       UI.user_error! "'release_notes' param must be supplied"
     #       next
     #   end
     #   if not tag
     #       UI.user_error! "'tag' param must be supplied"
     #       next
     #   end
     #   gradle(
     #   task: 'clean bundle',
     #   build_type: 'Release',
     #   project_dir: '.')
     #   set_github_release(
     #       api_token: ENV['GITHUB_FASTLANE_TOKEN'],
     #       name: "#{tag}",
     #       repository_name: "NYPL-Simplified/Simplified-Android-SimplyE",
     #       tag_name: "#{tag}",
     #       description: "#{release_notes}",
     #       commitish: "master"
     #   )
     #   upload_to_play_store(
     #       skip_upload_metadata: true,
     #       skip_upload_changelogs: true,
     #       skip_upload_images: true,
     #       skip_upload_screenshots: true,
     #       skip_upload_apk: true,
     #       skip_upload_aab: false,
     #       aab: 'app/build/outputs/bundle/release/simplye-5.0.0-beta001-4161-release.aab'
     #       )
     # end

end
