package org.nypl.simplified.tests.local.books.accounts

import org.nypl.simplified.tests.books.accounts.AccountProviderSourceNYPLRegistryDescriptionContract

class AccountProviderSourceNYPLRegistryDescriptionTest : AccountProviderSourceNYPLRegistryDescriptionContract()
