name: Android CI (Daily DRM-Free, JDK 15)

on:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build
        run: .ci/ci-main.sh pull-request
