name: Android CI (Daily Authenticated)

on:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        env:
          NYPL_NEXUS_USER:                  ${{ secrets.NYPL_NEXUS_USER }}
          NYPL_NEXUS_PASSWORD:              ${{ secrets.NYPL_NEXUS_PASSWORD }}
          MAVEN_CENTRAL_USERNAME:           ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD:           ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_STAGING_PROFILE_ID: 'af061f5afba777'
          MAVEN_CENTRAL_SIGNING_KEY_ID:     '0xF0E34285824ED500'
          NYPL_GITHUB_ACCESS_TOKEN:         ${{ secrets.NYPL_GITHUB_ACCESS_TOKEN }}
        run: .ci/ci-main.sh normal
