name: Android CI (Daily DRM-Free, JDK 11)

on:
  schedule:
    - cron:  '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Build
        run: .ci/ci-main.sh pull-request
