name: Android CI (Pull Requests) v2

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Reposistory
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Assemble
        run: .ci/ci-main.sh pull-request-v2

      - name: Test (configured)
        run: .ci/ci-test.sh pull-request

      - name: Test (default)
        run: ./gradlew testDebug -x :simplified-tests:testDebug

      - name: Legacy Tests
        run: ./gradlew :simplified-tests:test