name: Open eBooks Build & Test

on: push
# on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Reposistory
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build
        env:
          NYPL_S3_ACCESS_KEY:               ${{ secrets.NYPL_S3_ACCESS_KEY }}
          NYPL_S3_SECRET_ACCESS_KEY:        ${{ secrets.NYPL_S3_SECRET_ACCESS_KEY }}
          MAVEN_CENTRAL_USERNAME:           ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD:           ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_STAGING_PROFILE_ID: 'af061f5afba777'
          MAVEN_CENTRAL_SIGNING_KEY_ID:     'Library Simplified'
          NYPL_GITHUB_ACCESS_TOKEN:         ${{ secrets.NYPL_GITHUB_ACCESS_TOKEN }}
        run: bash ./gradlew :simplified-app-openebooks:assembleDebug --stacktrace

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

#      - name: Get reference to APK
#        uses: actions/upload-artifact@master
#        with:
#          name: openebooks-debug.apk
#          path: simplified-app-simplye/build/outputs/apk/debug/simplye-debug.apk

  unit_tests:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Reposistory
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Run tests
        run: ./gradlew clean testDebug

  distribute:
    needs: [ unit_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@main
        with:
          name: openebooks-debug.apk

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.OPENEBOOKS_FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: openebooks-qa
          file: openebooks-debug.apk
